<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Enums\InvoiceStatus;
use App\Enums\InvoiceType;
use App\Models\Company;
use App\Models\Currency;
use App\Models\Request;
use App\Models\SupplierInvoice;
use App\Models\SupplierOrder;
use App\Models\Team;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<SupplierInvoice>
 */
final class SupplierInvoiceFactory extends Factory
{
    protected $model = SupplierInvoice::class;

    /**
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        /** @var \DateTime $invoiceDate */
        $invoiceDate = $this->faker->dateTimeBetween('-30 days', 'now');
        $netDays = $this->faker->randomElement([15, 30, 45, 60]);

        return [
            // reference_number is auto-generated by observer
            'invoice_number' => $this->faker->unique()->numerify('INV-####'),
            'type' => InvoiceType::STANDARD,
            'status' => InvoiceStatus::DRAFT,
            'exchange_rate' => '1.00000000',
            'subtotal' => '0.0000',
            'tax_total' => '0.0000',
            'total' => '0.0000',
            'amount_paid' => '0.0000',
            'invoice_date' => $invoiceDate,
            'due_at' => (clone $invoiceDate)->modify("+{$netDays} days"),
            'net_days' => $netDays,
            'notes' => $this->faker->optional()->sentence(),
            'team_id' => Team::factory(),
            'creator_id' => User::factory(),
            'request_id' => Request::factory(),
            'supplier_id' => Company::factory()->supplier(),
            'supplier_order_id' => null,
            'currency_id' => Currency::factory(),
            'original_invoice_id' => null,
            'credit_reason' => null,
        ];
    }

    /**
     * Indicate that the invoice is a draft.
     */
    public function draft(): static
    {
        return $this->state(fn (array $attributes): array => [
            'status' => InvoiceStatus::DRAFT,
        ]);
    }

    /**
     * Indicate that the invoice has been sent/received.
     */
    public function sent(): static
    {
        return $this->state(fn (array $attributes): array => [
            'status' => InvoiceStatus::SENT,
        ]);
    }

    /**
     * Indicate that the invoice is partially paid.
     */
    public function partial(): static
    {
        return $this->state(function (array $attributes): array {
            $total = (float) ($attributes['total'] ?? 1000);
            $amountPaid = $total * $this->faker->randomFloat(2, 0.1, 0.9);

            return [
                'status' => InvoiceStatus::PARTIAL,
                'amount_paid' => (string) round($amountPaid, 4),
            ];
        });
    }

    /**
     * Indicate that the invoice is fully paid.
     */
    public function paid(): static
    {
        return $this->state(fn (array $attributes): array => [
            'status' => InvoiceStatus::PAID,
            'amount_paid' => $attributes['total'] ?? '0.0000',
        ]);
    }

    /**
     * Indicate that the invoice is overdue.
     */
    public function overdue(): static
    {
        return $this->state(fn (array $attributes): array => [
            'status' => InvoiceStatus::OVERDUE,
            'due_at' => now()->subDays($this->faker->numberBetween(1, 30)),
        ]);
    }

    /**
     * Indicate that the invoice is cancelled.
     */
    public function cancelled(): static
    {
        return $this->state(fn (array $attributes): array => [
            'status' => InvoiceStatus::CANCELLED,
        ]);
    }

    /**
     * Indicate a specific status.
     */
    public function withStatus(InvoiceStatus $status): static
    {
        return $this->state(fn (array $attributes): array => [
            'status' => $status,
        ]);
    }

    /**
     * Indicate that this is a prepayment invoice.
     */
    public function prepayment(): static
    {
        return $this->state(fn (array $attributes): array => [
            'type' => InvoiceType::PREPAYMENT,
        ]);
    }

    /**
     * Indicate that this is a balance invoice.
     */
    public function balance(): static
    {
        return $this->state(fn (array $attributes): array => [
            'type' => InvoiceType::BALANCE,
        ]);
    }

    /**
     * Indicate that this is a credit note.
     */
    public function creditNote(?SupplierInvoice $originalInvoice = null): static
    {
        return $this->state(fn (array $attributes): array => [
            'type' => InvoiceType::CREDIT_NOTE,
            'original_invoice_id' => $originalInvoice?->getKey(),
            'credit_reason' => $this->faker->sentence(),
        ]);
    }

    /**
     * Indicate that this is a debit note.
     */
    public function debitNote(): static
    {
        return $this->state(fn (array $attributes): array => [
            'type' => InvoiceType::DEBIT_NOTE,
        ]);
    }

    /**
     * Indicate a specific type.
     */
    public function withType(InvoiceType $type): static
    {
        return $this->state(fn (array $attributes): array => [
            'type' => $type,
        ]);
    }

    /**
     * Set specific totals.
     */
    public function withTotals(float $subtotal, float $taxTotal, float $total): static
    {
        return $this->state(fn (array $attributes): array => [
            'subtotal' => (string) $subtotal,
            'tax_total' => (string) $taxTotal,
            'total' => (string) $total,
        ]);
    }

    /**
     * Set exchange rate with base currency calculation.
     */
    public function withExchangeRate(float $rate): static
    {
        return $this->state(fn (array $attributes): array => [
            'exchange_rate' => (string) $rate,
        ]);
    }

    /**
     * Associate with a specific request.
     */
    public function forRequest(?Request $request = null): static
    {
        return $this->state(fn (array $attributes): array => [
            'request_id' => $request ?? Request::factory(),
        ]);
    }

    /**
     * Associate with a specific supplier.
     */
    public function forSupplier(?Company $supplier = null): static
    {
        return $this->state(fn (array $attributes): array => [
            'supplier_id' => $supplier ?? Company::factory()->supplier(),
        ]);
    }

    /**
     * Associate with a specific supplier order.
     */
    public function forSupplierOrder(?SupplierOrder $order = null): static
    {
        return $this->state(fn (array $attributes): array => [
            'supplier_order_id' => $order ?? SupplierOrder::factory(),
        ]);
    }

    /**
     * Associate with a specific currency.
     */
    public function withCurrency(?Currency $currency = null): static
    {
        return $this->state(fn (array $attributes): array => [
            'currency_id' => $currency ?? Currency::factory(),
        ]);
    }

    /**
     * Set payment terms.
     */
    public function withNetDays(int $days): static
    {
        return $this->state(function (array $attributes) use ($days): array {
            $invoiceDate = $attributes['invoice_date'] ?? now();

            return [
                'net_days' => $days,
                'due_at' => $invoiceDate instanceof \DateTime
                    ? (clone $invoiceDate)->modify("+{$days} days")
                    : now()->addDays($days),
            ];
        });
    }

    /**
     * Set the invoice as due today.
     */
    public function dueToday(): static
    {
        return $this->state(fn (array $attributes): array => [
            'due_at' => now(),
        ]);
    }

    /**
     * Set the invoice as due in the past.
     */
    public function duePast(int $daysAgo = 30): static
    {
        return $this->state(fn (array $attributes): array => [
            'due_at' => now()->subDays($daysAgo),
        ]);
    }

    /**
     * Set the invoice as due in the future.
     */
    public function dueFuture(int $daysFromNow = 30): static
    {
        return $this->state(fn (array $attributes): array => [
            'due_at' => now()->addDays($daysFromNow),
        ]);
    }
}
