<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Enums\PaymentMethod;
use App\Models\SupplierInvoice;
use App\Models\SupplierPayment;
use App\Models\Team;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<SupplierPayment>
 */
final class SupplierPaymentFactory extends Factory
{
    protected $model = SupplierPayment::class;

    /**
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            // payment_number is auto-generated by observer
            'payment_method' => $this->faker->randomElement(PaymentMethod::cases()),
            'amount' => (string) $this->faker->randomFloat(2, 100, 10000),
            'payment_date' => $this->faker->dateTimeBetween('-30 days', 'now'),
            'reference_number' => $this->faker->optional()->numerify('REF-####'),
            'notes' => $this->faker->optional()->sentence(),
            'team_id' => Team::factory(),
            'creator_id' => User::factory(),
            'supplier_invoice_id' => SupplierInvoice::factory(),
        ];
    }

    /**
     * Associate with a specific supplier invoice.
     */
    public function forSupplierInvoice(?SupplierInvoice $invoice = null): static
    {
        return $this->state(fn (array $attributes): array => [
            'supplier_invoice_id' => $invoice ?? SupplierInvoice::factory(),
        ]);
    }

    /**
     * Set payment method to bank transfer.
     */
    public function bankTransfer(): static
    {
        return $this->state(fn (array $attributes): array => [
            'payment_method' => PaymentMethod::BANK_TRANSFER,
        ]);
    }

    /**
     * Set payment method to cash.
     */
    public function cash(): static
    {
        return $this->state(fn (array $attributes): array => [
            'payment_method' => PaymentMethod::CASH,
        ]);
    }

    /**
     * Set payment method to check.
     */
    public function check(): static
    {
        return $this->state(fn (array $attributes): array => [
            'payment_method' => PaymentMethod::CHECK,
        ]);
    }

    /**
     * Set payment method to letter of credit.
     */
    public function letterOfCredit(): static
    {
        return $this->state(fn (array $attributes): array => [
            'payment_method' => PaymentMethod::LC,
        ]);
    }

    /**
     * Set a specific payment method.
     */
    public function withPaymentMethod(PaymentMethod $method): static
    {
        return $this->state(fn (array $attributes): array => [
            'payment_method' => $method,
        ]);
    }

    /**
     * Set a specific amount.
     */
    public function withAmount(float $amount): static
    {
        return $this->state(fn (array $attributes): array => [
            'amount' => (string) $amount,
        ]);
    }

    /**
     * Set payment date to today.
     */
    public function paidToday(): static
    {
        return $this->state(fn (array $attributes): array => [
            'payment_date' => now(),
        ]);
    }

    /**
     * Set payment date to a specific date.
     */
    public function paidOn(\DateTimeInterface $date): static
    {
        return $this->state(fn (array $attributes): array => [
            'payment_date' => $date,
        ]);
    }

    /**
     * Set a reference number.
     */
    public function withReference(string $reference): static
    {
        return $this->state(fn (array $attributes): array => [
            'reference_number' => $reference,
        ]);
    }

    /**
     * Create a full payment for the invoice total.
     */
    public function fullPayment(): static
    {
        return $this->state(
            // This will be resolved when the model is created

            fn (array $attributes): array => [])->afterCreating(function (SupplierPayment $payment): void {
                $invoice = $payment->supplierInvoice;
                if ($invoice !== null) {
                    $amountOutstanding = (float) $invoice->total - (float) $invoice->amount_paid + (float) $payment->amount;
                    $payment->amount = (string) max(0, $amountOutstanding);
                    $payment->saveQuietly();
                }
            });
    }

    /**
     * Create a partial payment (50% of outstanding).
     */
    public function partialPayment(): static
    {
        return $this->afterCreating(function (SupplierPayment $payment): void {
            $invoice = $payment->supplierInvoice;
            if ($invoice !== null) {
                $amountOutstanding = (float) $invoice->total - (float) $invoice->amount_paid + (float) $payment->amount;
                $payment->amount = (string) max(0, $amountOutstanding * 0.5);
                $payment->saveQuietly();
            }
        });
    }
}
