<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Enums\OrderStatus;
use App\Models\Currency;
use App\Models\Request;
use App\Models\Supplier;
use App\Models\SupplierOrder;
use App\Models\SupplierQuote;
use App\Models\Team;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<SupplierOrder>
 */
final class SupplierOrderFactory extends Factory
{
    protected $model = SupplierOrder::class;

    /**
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            // po_number is auto-generated by observer
            'status' => OrderStatus::DRAFT,
            'exchange_rate' => '1.00000000',
            'subtotal' => '0.0000',
            'tax_total' => '0.0000',
            'total' => '0.0000',
            'base_subtotal' => '0.0000',
            'base_tax_total' => '0.0000',
            'base_total' => '0.0000',
            'payment_terms_days' => 30,
            'payment_terms_text' => $this->faker->optional()->randomElement(['Net 30', 'Net 60', 'Due on Receipt']),
            'expected_delivery_date' => $this->faker->optional()->dateTimeBetween('+7 days', '+90 days'),
            'notes' => $this->faker->optional()->sentence(),
            'internal_notes' => $this->faker->optional()->sentence(),
            'ordered_at' => null,
            'confirmed_at' => null,
            'team_id' => Team::factory(),
            'creator_id' => User::factory(),
            'request_id' => Request::factory(),
            'supplier_id' => Supplier::factory(),
            'supplier_quote_id' => null,
            'currency_id' => Currency::factory(),
        ];
    }

    /**
     * Indicate that the order is a draft.
     */
    public function draft(): static
    {
        return $this->state(fn (array $attributes): array => [
            'status' => OrderStatus::DRAFT,
        ]);
    }

    /**
     * Indicate that the order is confirmed.
     */
    public function confirmed(): static
    {
        return $this->state(fn (array $attributes): array => [
            'status' => OrderStatus::CONFIRMED,
            'confirmed_at' => now(),
        ]);
    }

    /**
     * Indicate that the order is processing.
     */
    public function processing(): static
    {
        return $this->state(fn (array $attributes): array => [
            'status' => OrderStatus::PROCESSING,
            'confirmed_at' => now()->subDays(2),
            'ordered_at' => now()->subDay(),
        ]);
    }

    /**
     * Indicate that the order is completed.
     */
    public function completed(): static
    {
        return $this->state(fn (array $attributes): array => [
            'status' => OrderStatus::COMPLETED,
            'confirmed_at' => now()->subDays(30),
            'ordered_at' => now()->subDays(28),
        ]);
    }

    /**
     * Indicate that the order is cancelled.
     */
    public function cancelled(): static
    {
        return $this->state(fn (array $attributes): array => [
            'status' => OrderStatus::CANCELLED,
        ]);
    }

    /**
     * Indicate a specific status.
     */
    public function withStatus(OrderStatus $status): static
    {
        return $this->state(fn (array $attributes): array => [
            'status' => $status,
        ]);
    }

    /**
     * Set specific totals.
     */
    public function withTotals(float $subtotal, float $taxTotal, float $total): static
    {
        return $this->state(fn (array $attributes): array => [
            'subtotal' => (string) $subtotal,
            'tax_total' => (string) $taxTotal,
            'total' => (string) $total,
            'base_subtotal' => (string) $subtotal,
            'base_tax_total' => (string) $taxTotal,
            'base_total' => (string) $total,
        ]);
    }

    /**
     * Set exchange rate with base currency calculation.
     */
    public function withExchangeRate(float $rate): static
    {
        return $this->state(function (array $attributes) use ($rate): array {
            $subtotal = (float) ($attributes['subtotal'] ?? 0);
            $taxTotal = (float) ($attributes['tax_total'] ?? 0);
            $total = (float) ($attributes['total'] ?? 0);

            return [
                'exchange_rate' => (string) $rate,
                'base_subtotal' => (string) ($subtotal * $rate),
                'base_tax_total' => (string) ($taxTotal * $rate),
                'base_total' => (string) ($total * $rate),
            ];
        });
    }

    /**
     * Associate with a specific request.
     */
    public function forRequest(?Request $request = null): static
    {
        return $this->state(fn (array $attributes): array => [
            'request_id' => $request ?? Request::factory(),
        ]);
    }

    /**
     * Associate with a specific supplier.
     */
    public function forSupplier(?Supplier $supplier = null): static
    {
        return $this->state(fn (array $attributes): array => [
            'supplier_id' => $supplier ?? Supplier::factory(),
        ]);
    }

    /**
     * Associate with a specific supplier quote.
     */
    public function fromQuote(?SupplierQuote $quote = null): static
    {
        return $this->state(fn (array $attributes): array => [
            'supplier_quote_id' => $quote ?? SupplierQuote::factory(),
        ]);
    }

    /**
     * Associate with a specific currency.
     */
    public function withCurrency(?Currency $currency = null): static
    {
        return $this->state(fn (array $attributes): array => [
            'currency_id' => $currency ?? Currency::factory(),
        ]);
    }

    /**
     * Set payment terms.
     */
    public function withPaymentTerms(int $days, ?string $text = null): static
    {
        return $this->state(fn (array $attributes): array => [
            'payment_terms_days' => $days,
            'payment_terms_text' => $text ?? 'Net '.$days,
        ]);
    }

    /**
     * Mark as ordered with timestamp.
     */
    public function ordered(): static
    {
        return $this->state(fn (array $attributes): array => [
            'ordered_at' => now(),
            'status' => OrderStatus::CONFIRMED,
            'confirmed_at' => now(),
        ]);
    }
}
